version: "1"
services:
  animation-live:
    build:
      context: .
    ports:
      - 8080
    resources:
      cpu: 1000
      memory: 1024
    scaling:
      min: 1
      max: 1
    health:
      path: /
      port: 8080